DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PRICE_LISTS;

CREATE TABLE PRICE_LISTS (
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRICE_LIST_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(11,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,

    CONSTRAINT FK_BRAND_ID FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    CONSTRAINT FK_PRICE_LIST_ID FOREIGN KEY (PRICE_LIST_ID) REFERENCES PRICE_LISTS(ID)
);
